/**
 * @description Adds two numbers and returns the result
 * @param {number} a - The first number
 * @param {number} b - The second number
 * @returns {number} The sum of a and b
 * @throws {TypeError} If either argument is not a number
 * @example
 * // Returns 3
 * add(1, 2);
 */
function add(a, b) {
  // Generated by Copilot
  if (typeof a !== 'number' || typeof b !== 'number') {
    throw new TypeError('Both arguments must be numbers');
  }
  return a + b;
}

function testFunction() {
  console.log('Hello from testFunction in utils.cjs');
  return true;
}

module.exports = {
  // Generated by Copilot
  add,
  testFunction
};
